#!/bin/bash
# exe-dev-setup.sh — Setup script for C3PO on exe.dev VM.
#
# Run this AFTER cloning the repo on the VM:
#   cd ~/nunes-celio-c3po && bash deploy/exe-dev-setup.sh
#
# Prerequisites:
#   - exe.dev VM with SSH access
#   - Repo cloned to ~/nunes-celio-c3po
#   - config/people.json populated with real data
#   - ANTHROPIC_API_KEY set in environment

set -euo pipefail

REPO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
echo "=== C3PO Setup on exe.dev ==="
echo "Repo: $REPO_DIR"
echo ""

# --- 1. Check prerequisites ---
echo "--- [1/8] Checking prerequisites..."

if [ ! -f "$REPO_DIR/config/people.json" ]; then
    echo "ERROR: config/people.json not found."
    echo "Copy config/people.json.example to config/people.json and fill in real data."
    exit 1
fi

if [ -z "${ANTHROPIC_API_KEY:-}" ]; then
    echo "WARNING: ANTHROPIC_API_KEY not set. Set it before starting the gateway."
    echo '  echo '\''export ANTHROPIC_API_KEY="sk-ant-..."'\'' >> ~/.bashrc && source ~/.bashrc'
fi

# Gateway auth password (required for production security)
ENV_DIR="$HOME/.config/c3po"
ENV_FILE="$ENV_DIR/.env"
if [ ! -f "$ENV_FILE" ]; then
    echo "Creating gateway environment file at $ENV_FILE..."
    mkdir -p "$ENV_DIR"
    GENERATED_PW=$(openssl rand -base64 32)
    cat > "$ENV_FILE" <<ENVEOF
# C3PO Gateway environment (auto-generated by exe-dev-setup.sh)
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-sk-ant-CHANGE-ME}
GATEWAY_PASSWORD=${GENERATED_PW}
GATEWAY_PORT=18789
ENVEOF
    chmod 600 "$ENV_FILE"
    echo "Generated gateway password. Edit $ENV_FILE if needed."
elif ! grep -q "GATEWAY_PASSWORD" "$ENV_FILE"; then
    GENERATED_PW=$(openssl rand -base64 32)
    echo "GATEWAY_PASSWORD=${GENERATED_PW}" >> "$ENV_FILE"
    echo "Added GATEWAY_PASSWORD to $ENV_FILE."
fi

# --- 2. Install Bun if needed ---
echo "--- [2/8] Checking Bun..."

if command -v bun >/dev/null 2>&1; then
    BUN_VERSION=$(bun --version)
    echo "Bun $BUN_VERSION found."
else
    echo "Installing Bun..."
    curl -fsSL https://bun.sh/install | bash
    export PATH="$HOME/.bun/bin:$PATH"
    echo "Bun installed."
fi

# --- 3. Install OpenClaw ---
echo "--- [3/8] Installing OpenClaw..."

# Minimum version: 2026.1.29 (patches CVE-2026-25253 — 1-click RCE via WebSocket hijacking)
OPENCLAW_VERSION="2026.1.29"

if command -v openclaw >/dev/null 2>&1; then
    INSTALLED_VERSION=$(openclaw --version 2>/dev/null || echo "unknown")
    echo "OpenClaw already installed: $INSTALLED_VERSION"
    echo "Minimum required: $OPENCLAW_VERSION (CVE-2026-25253 fix)"
else
    # OpenClaw is distributed via npm; use bun to install globally
    bun install -g "openclaw@^${OPENCLAW_VERSION}"
    echo "OpenClaw $OPENCLAW_VERSION installed."
fi

# --- 4. Install dependencies ---
echo "--- [4/8] Installing dependencies..."

cd "$REPO_DIR"
if [ ! -d "node_modules/googleapis" ]; then
    bun install
    echo "Dependencies installed."
else
    echo "Dependencies already installed."
fi

# --- 5. Install Playwright + Chromium (for browser automation) ---
echo "--- [5/10] Installing Playwright and Chromium..."

if npx playwright --version >/dev/null 2>&1; then
    echo "Playwright already installed."
else
    npm install -g playwright
    echo "Playwright installed."
fi

# Install Chromium browser binary (needed for headless automation).
npx playwright install --with-deps chromium 2>/dev/null || npx playwright install chromium
echo "Chromium browser installed for Playwright."

# --- 6. Set timezone ---
echo "--- [6/10] Setting timezone to America/Sao_Paulo..."

sudo timedatectl set-timezone America/Sao_Paulo 2>/dev/null || echo "Could not set timezone (non-fatal)."

# --- 7. Render config files ---
echo "--- [7/10] Rendering config files..."

bun "$REPO_DIR/scripts/render-files.ts"

# --- 8. Deploy OpenClaw config ---
echo "--- [8/10] Deploying OpenClaw config..."

mkdir -p ~/.openclaw
cp "$REPO_DIR/openclaw/openclaw.json5.local" ~/.openclaw/openclaw.json
cp "$REPO_DIR/openclaw/exec-approvals.local.json" ~/.openclaw/exec-approvals.json
echo "Config copied to ~/.openclaw/"

# --- 9. Verify browser setup ---
echo "--- [9/10] Verifying browser setup..."

if openclaw browser start --headless 2>/dev/null; then
    echo "Browser started successfully (headless)."
    openclaw browser stop 2>/dev/null || true
else
    echo "WARNING: Could not start browser (non-fatal). Verify after setup."
fi

# --- 10. Install systemd services ---
echo "--- [10/10] Installing systemd services..."

SYSTEMD_DIR="$HOME/.config/systemd/user"
mkdir -p "$SYSTEMD_DIR"

# Gateway (fallback if `openclaw gateway install` doesn't exist)
if [ -f "$REPO_DIR/scripts/systemd/c3po-gateway.local.service" ]; then
    cp "$REPO_DIR/scripts/systemd/c3po-gateway.local.service" "$SYSTEMD_DIR/c3po-gateway.service"
fi

# Memory archive
if [ -f "$REPO_DIR/scripts/systemd/c3po-memory-archive.local.service" ]; then
    cp "$REPO_DIR/scripts/systemd/c3po-memory-archive.local.service" "$SYSTEMD_DIR/c3po-memory-archive.service"
fi
if [ -f "$REPO_DIR/scripts/systemd/c3po-memory-archive.local.timer" ]; then
    cp "$REPO_DIR/scripts/systemd/c3po-memory-archive.local.timer" "$SYSTEMD_DIR/c3po-memory-archive.timer"
fi

# Watchdog
if [ -f "$REPO_DIR/scripts/systemd/c3po-watchdog.local.service" ]; then
    cp "$REPO_DIR/scripts/systemd/c3po-watchdog.local.service" "$SYSTEMD_DIR/c3po-watchdog.service"
fi
if [ -f "$REPO_DIR/scripts/systemd/c3po-watchdog.timer" ]; then
    cp "$REPO_DIR/scripts/systemd/c3po-watchdog.timer" "$SYSTEMD_DIR/c3po-watchdog.timer"
fi

# Workspace backup (daily git commit + push of kb/ and memory/)
if [ -f "$REPO_DIR/scripts/systemd/c3po-workspace-backup.local.service" ]; then
    cp "$REPO_DIR/scripts/systemd/c3po-workspace-backup.local.service" "$SYSTEMD_DIR/c3po-workspace-backup.service"
fi
if [ -f "$REPO_DIR/scripts/systemd/c3po-workspace-backup.timer" ]; then
    cp "$REPO_DIR/scripts/systemd/c3po-workspace-backup.timer" "$SYSTEMD_DIR/c3po-workspace-backup.timer"
fi

# Reload and enable
systemctl --user daemon-reload

# Try to enable lingering (survives logout)
sudo loginctl enable-linger "$(whoami)" 2>/dev/null || echo "Could not enable lingering (non-fatal)."

# Enable timers
systemctl --user enable c3po-memory-archive.timer 2>/dev/null || true
systemctl --user start c3po-memory-archive.timer 2>/dev/null || true
systemctl --user enable c3po-watchdog.timer 2>/dev/null || true
systemctl --user start c3po-watchdog.timer 2>/dev/null || true
systemctl --user enable c3po-workspace-backup.timer 2>/dev/null || true
systemctl --user start c3po-workspace-backup.timer 2>/dev/null || true

echo ""
echo "=== Setup complete! ==="
echo ""
echo "Next steps (manual):"
echo "  1. Connect WhatsApp:  openclaw channels login"
echo "  2. Get group JID:     openclaw channels whatsapp groups"
echo "  3. Update config/people.json with the real group JID"
echo "  4. Re-render:         bun scripts/render-files.ts"
echo "  5. Re-copy config:    cp openclaw/openclaw.json5.local ~/.openclaw/openclaw.json"
echo "  6. Start gateway:     openclaw gateway --port 18789"
echo "     (or: systemctl --user enable --now c3po-gateway)"
echo "  7. Test WhatsApp:     Send a WhatsApp message to the bot"
echo "  8. Test browser:      openclaw browser start && openclaw browser open https://example.com && openclaw browser snapshot"
echo ""
echo "For Google Calendar setup, see: scripts/setup-exe-dev.md"
